{% set version = "2.5.0" %}
{% set dart_archive = "https://storage.googleapis.com/dart-archive/channels/stable/release/" %}

package:
  name: dart-sdk
  version: {{ version }}

source:
  url: https://github.com/dart-lang/sdk/archive/{{ version }}.tar.gz  # [win64]
  sha256: ed528241c50a8f454852c6d361bb57c168861bbeb17cb81026aa59c16e478f1b  # [win64]
  folder: dart_sdk
  url: https://storage.googleapis.com/chrome-infra/depot_tools.zip  # [win64]
  sha256: 96f2453ba90c2e845ddd68d67d16d0ac6cf8abc66e62a2446ccf6d718c2d2ad2  # [win64]
  folder: depot_tools

build:
  number: 0
  skip: True  # [not linux64 and not osx and not win64]
  run_exports:
    - dark-sdk
  # binary_relocation: False

requirements:
  build:
    - {{ compiler('c') }}
    - python 3.6
    -
test:
  files:
    - hello-world.dart
  commands:
    - dart --version
    - dart hello-world.dart
    - dartfmt --version
    - pub --version

about:
  home: https://dart.dev
  license: BSD-3-Clause
  license_family: BSD
  license_file: dart_sdk/LICENSE
  summary: The Dart SDK is a set of tools and libraries for the Dart programming language.
  doc_url: https://dart.dev/guides
  dev_url: https://github.com/dart-lang/sdk

extra:
  recipe-maintainers:
    - carterbox
