{% set version = "0.9.4" %}

# As of June 2023, opensycl is not tested against any llvm later than 14
{% set llvm_version = "15" %}

{% if cuda_compiler_version is not defined %}
  {% set cuda_compiler_version = "None" %}
{% endif %}
{% set cuda_major = environ.get("cuda_compiler_version", "0.0").split(".")[0]|int %}

package:
  name: opensycl-split
  version: {{ version }}

source:
  url: https://github.com/OpenSYCL/OpenSYCL/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6262533191c812966e2f8b67e6ae510ae5ad2cf7e0caecc9957e8a69423e51c4
  patches:
    - findcuda.patch

build:
  number: 0
  skip: true  # [cuda_compiler_version != "None"]
  script_env:
    - CMAKE_GENERATOR=Ninja
    - WITH_CUDA_BACKEND=ON   # [cuda_compiler_version != "None"]
    - WITH_CUDA_BACKEND=OFF  # [cuda_compiler_version == "None"]
  has_prefix_files:
    - /etc/hipSYCL/syclcc.json

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - ninja
  host:
{% if cuda_major == 12 %}
    - cuda-cudart-dev
    - cuda-driver-dev
{% endif %}
    - boost-cpp
    - clangdev {{ llvm_version }}
    - llvmdev {{ llvm_version }}

outputs:

  - name: libhipsycl
    run_exports:
      - {{ pin_subpackage('libhipsycl', max_pin='x.x.x') }}
    files:
      - lib/hipSYCL/
      - lib/libhipSYCL*
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
      host:
{% if cuda_major == 12 %}
        - cuda-cudart-dev
        - cuda-driver-dev
{% endif %}

  - name: opensycl
    run_exports:
      - {{ pin_subpackage('libhipsycl', max_pin='x.x.x') }}
    files:
      - bin/hipsycl*
      - bin/syclcc*
      - etc/hipSYCL/
      - include/CL/
      - include/hipSYCL/
      - include/sycl/
      - include/SYCL/
      - lib/cmake/hipSYCL/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
      host:
        - {{ pin_subpackage('libhipsycl', exact=True) }}
        - boost-cpp
        - clangdev {{ llvm_version }}
        - llvmdev {{ llvm_version }}
      run:
        - {{ pin_subpackage('libhipsycl', exact=True) }}
      # OpenSYCL headers include the following headers, so need them when
      # compiling with syclcc
        - boost-cpp
        - llvm-openmp
      # bin/syclcc* are python script wrappers around the host compiler
        - python =3.*
      run_constrained:
      # clang++ is needed in addition to the host compiler only for certain
      # sycl targets
        - clangxx {{ llvm_version }}

    test:
      script: run_test.sh
      requires:
      # The CXX compiler is a host compiler, so like CUDA, you must depend on it
      # separately
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
        - clangxx
        - cmake
        - ninja
      source_files:
        - tests/

about:
  home: https://github.com/OpenSYCL/OpenSYCL
  summary: 'Multi-backend implementation of SYCL for CPUs and GPUs'
  description: |
    Open SYCL is a modern SYCL implementation targeting CPUs and GPUs from all
    major vendors that supports many use cases and approaches for implementing
    SYCL:

    1. A generic, single-pass compiler infrastructure that compiles kernels to
    a unified code representation that is then lowered at runtime to target
    devices, providing a high degree of portability, low compilation times,
    flexibility and extensibility.

    2. Additionally, Open SYCL can aggregate existing clang toolchains and
    augment them with support for SYCL constructs. This allows for a high
    degree of interoperability between SYCL and other models such as CUDA or
    HIP.

    3. Or Open SYCL can be used in library-only compilation flows. In these
    compilation flows, Open SYCL acts as a C++ library for third-party
    compilers. This can have portability advantages or simplify deployment.

  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/OpenSYCL/OpenSYCL

extra:
  recipe-maintainers:
    - carterbox
  feedstock-name:
    - opensycl
