{% set version = "3.0.0" %}
{% set so_major = "3" %}

package:
  name: libptl-split
  version: {{ version }}

source:
  url: https://github.com/jrmadsen/PTL/archive/f892a93d79615ed8f51c1b9c71f0f7b771dd8223.tar.gz
  sha256: a272fb95af0eddccb881c4c65cda0f0fe7ce7900559e953e56408824dbc556e3

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  host:
    - tbb-devel

outputs:
  - name: {{ 'libptl' ~ so_major }}
    files:
      - lib/libptl.so*       # [linux]
      - lib/libptl.*dylib    # [osx]
      - Library/bin/ptl.dll  # [win]
      - Library/lib/ptl.lib  # [win]
    build:
      run_exports:
        - {{ pin_subpackage( 'libptl' ~ so_major) }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - tbb-devel
    test:
      commands:
        - test -f $PREFIX/lib/libptl$SHLIB_EXT             # [unix]
        - test ! -f $PREFIX/lib/libptl.a                   # [unix]
        - test -f $PREFIX/lib/libptl.so.{{ so_major }}     # [linux]
        - test -f $PREFIX/lib/libptl.{{ so_major }}.dylib  # [osx]
        - test ! -f $PREFIX/include/PTL/PTL.hh               # [unix]
        - test ! -f $PREFIX/lib/cmake/PTL/PTLConfig.cmake    # [unix]
        - test ! -f $PREFIX/lib/pkgconfig/ptl.pc             # [unix]

        - if not exist %LIBRARY_LIB%\\ptl.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\ptl.dll exit 1  # [win]
        - if exist %LIBRARY_INC%\\PTL\\PTL.hh exit 1  # [win]
        - if exist %LIBRARY_LIB%\\cmake\\plt\\PTLConfig.cmake exit 1  # [win]

  - name: libptl
    files:
      - include/PTL           # [unix]
      - lib/cmake/PTL         # [unix]
      - lib/pkgconfig/ptl.pc  # [unix]
      - Library/include/PTL           # [win]
      - Library/lib/cmake/PTL         # [win]
      - Library/lib/pkgconfig/ptl.pc  # [win]
    build:
      run_exports:
        - {{ pin_subpackage( 'libptl' ~ so_major) }}
    requirements:
      build:
        - cmake
        - ninja
      host:
        - {{ pin_subpackage( 'libptl' ~ so_major, exact=True) }}
      run:
        - {{ pin_subpackage( 'libptl' ~ so_major, exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/libptl$SHLIB_EXT             # [unix]
        - test ! -f $PREFIX/lib/libptl.a                   # [unix]
        - test -f $PREFIX/lib/libptl.so.{{ so_major }}     # [linux]
        - test -f $PREFIX/lib/libptl.{{ so_major }}.dylib  # [osx]
        - test -f $PREFIX/include/PTL/PTL.hh               # [unix]
        - test -f $PREFIX/lib/cmake/PTL/PTLConfig.cmake    # [unix]
        - test -f $PREFIX/lib/pkgconfig/ptl.pc             # [unix]

        - if not exist %LIBRARY_LIB%\\ptl.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\ptl.dll exit 1  # [win]
        - if not exist %LIBRARY_INC%\\PTL\\PTL.hh exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\cmake\\plt\\PTLConfig.cmake exit 1  # [win]

about:
  home: https://github.com/jrmadsen/PTL
  summary: 'Lightweight C++11 mutilthreading tasking system featuring thread-pool, task-groups, and lock-free task queue'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/jrmadsen/PTL

extra:
  feedstock-name: ptl
  recipe-maintainers:
    - carterbox
    - conda-forge/tomopy
