{% set name = "PTL" %}
{% set version = "2.3.3" %}
{% set so_major = "2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jrmadsen/PTL/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3275ad8ec2971c89aacb3b922717dc4e774fa4e59fc3f4035053225c802aee52

build:
  number: 0
  run_exports:
    - {{ pin_subpackage( name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - cmake

test:
  commands:
    - test -f $PREFIX/lib/libptl$SHLIB_EXT             # [unix]
    - test ! -f $PREFIX/lib/libptl.a                   # [unix]
    - test -f $PREFIX/lib/libptl.so.{{ so_major }}     # [linux]
    - test -f $PREFIX/lib/libptl.{{ so_major }}.dylib  # [osx]
    - test -f $PREFIX/include/PTL/PTL.hh               # [unix]
    - test -f $PREFIX/lib/cmake/PTL/PTLConfig.cmake    # [unix]
    - test -f $PREFIX/lib/pkgconfig/ptl.pc             # [unix]

    - if not exist %LIBRARY_LIB%\\ptl.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\ptl.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\PTL\\PTL.hh exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\plt\\PTLConfig.cmake exit 1  # [win]

about:
  home: https://github.com/jrmadsen/PTL
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    Parallel Tasking Library (PTL) - Lightweight C++11 mutilthreading tasking
    system featuring thread-pool, task-groups, and lock-free task queue
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/jrmadsen/PTL

extra:
  recipe-maintainers:
    - carterbox
    - conda-forge/tomopy
